version: '3.7'
networks:
  jenkins-maya:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.16.11.0/24
          gateway: 172.16.11.1
        - subnet: "2001:3984:3989::/64"
          gateway: "2001:3984:3989::1"

services:
  maya-jenkins:
    image: cinar/jenkins:maya-1.1
    privileged: true
    restart: unless-stopped
    extra_hosts:
      - "bitbucket.ulakhaberlesme.com.tr:192.168.10.14"
    networks:
      jenkins-maya:
        ipv4_address: 172.16.11.2
    ports:
      - 82:8090
      - 50002:50000
    container_name: maya-jenkins
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true -Dpermissive-script-security.enabled=true -Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--httpListenAddress=0.0.0.0 --httpPort=8090 --argumentsRealm.roles.user=devops --argumentsRealm.passwd.devops=sifre --argumentsRealm.roles.devops=admin
    volumes:
      - maya-home:/usr/share/jenkins
      - ./volume/maya/certs/ulakhaberlesme.crt:/usr/local/share/ca-certificates/ulakhaberlesme.crt
      - ./volume/maya/cascs/casc-ldap-ittest.yaml:/usr/share/jenkins/casc.yaml
      # MAYA secret bilgileri
      - ./volume/maya/secret/secret.key:/usr/share/jenkins/secret.key
      - ./volume/maya/secret/secrets:/usr/share/jenkins/secrets


volumes:
  maya-home:
